"""PR description and review comment generation for branding merge results."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .confidence import ConfidenceLevel
    from .resolver import MergeResult, Resolution


def generate_pr_title(upstream_ref: str) -> str:
    """Generate a concise PR title for the upstream sync.

    Args:
        upstream_ref: The upstream tag or commit reference being merged.

    Returns:
        A PR title string.
    """
    return f"chore: sync upstream {upstream_ref} with Davinci Sign branding"


def generate_pr_body(result: MergeResult, upstream_ref: str) -> str:
    """Generate a detailed PR body with resolution statistics.

    Args:
        result: The completed merge result.
        upstream_ref: The upstream tag or commit reference.

    Returns:
        Markdown-formatted PR body.
    """
    from .confidence import ConfidenceLevel

    # Bucket resolutions by confidence.
    high: list[Resolution] = []
    medium: list[Resolution] = []
    low_or_flagged: list[Resolution] = []

    for res in result.resolutions:
        if res.action == "flag_for_review" or res.confidence == ConfidenceLevel.LOW:
            low_or_flagged.append(res)
        elif res.confidence == ConfidenceLevel.HIGH:
            high.append(res)
        elif res.confidence == ConfidenceLevel.MEDIUM:
            medium.append(res)
        else:
            low_or_flagged.append(res)

    lines: list[str] = []

    # Header.
    lines.append(f"## Upstream Sync: `{upstream_ref}`")
    lines.append("")
    lines.append(
        f"**{result.total_files}** conflicted files processed "
        f"| **{result.auto_resolved}** auto-resolved "
        f"| **{result.flagged_for_review}** flagged for review"
    )
    lines.append("")

    # Confidence breakdown.
    lines.append("### Confidence Breakdown")
    lines.append("")
    lines.append(f"| Level | Count |")
    lines.append(f"|-------|-------|")
    lines.append(f"| High  | {len(high)} |")
    lines.append(f"| Medium | {len(medium)} |")
    lines.append(f"| Low / Flagged | {len(low_or_flagged)} |")
    lines.append("")

    # Auto-resolved (high confidence).
    if high:
        lines.append("### Auto-Resolved (High Confidence)")
        lines.append("")
        for res in high:
            lines.append(f"- `{res.file_path}` — {res.action}: {res.explanation}")
        lines.append("")

    # Needs spot-check (medium confidence).
    if medium:
        lines.append("### Needs Spot-Check (Medium Confidence)")
        lines.append("")
        for res in medium:
            lines.append(f"- `{res.file_path}` — {res.action}: {res.explanation}")
            if res.validation_errors:
                for err in res.validation_errors:
                    lines.append(f"  - :warning: {err}")
        lines.append("")

    # Requires manual review (low / flagged).
    if low_or_flagged:
        lines.append("### Requires Manual Review")
        lines.append("")
        for res in low_or_flagged:
            lines.append(f"- `{res.file_path}` — {res.action}: {res.explanation}")
            if res.validation_errors:
                for err in res.validation_errors:
                    lines.append(f"  - :warning: {err}")
        lines.append("")

    # Unresolvable files.
    if result.unresolvable_files:
        lines.append("### :x: Unresolvable Files")
        lines.append("")
        for f in result.unresolvable_files:
            lines.append(f"- `{f}` — requires manual resolution")
        lines.append("")

    # API usage and cost.
    lines.append("### API Usage")
    lines.append("")
    lines.append(f"- API calls: {result.api_calls_made}")
    lines.append(f"- Input tokens: {result.total_input_tokens:,}")
    lines.append(f"- Output tokens: {result.total_output_tokens:,}")
    lines.append(f"- Cost: ${result.total_cost_usd:.4f} USD")
    if result.tier_stats:
        tier_parts = [f"{k}: {v}" for k, v in result.tier_stats.items()]
        lines.append(f"- Tiers: {', '.join(tier_parts)}")
    lines.append("")

    # Footer.
    lines.append("---")
    lines.append("*Generated by branding-resolver agent*")

    return "\n".join(lines)


def generate_review_comment(resolution: Resolution) -> str:
    """Generate an inline PR review comment for a flagged resolution.

    Args:
        resolution: The resolution that needs human attention.

    Returns:
        Markdown-formatted review comment.
    """
    lines: list[str] = []

    lines.append(f"**Branding Resolver — {resolution.action.upper()}**")
    lines.append("")
    lines.append(f"**Category:** {resolution.category}")
    lines.append(f"**Reason:** {resolution.explanation}")
    lines.append("")

    if resolution.validation_errors:
        lines.append("**Validation Warnings:**")
        for err in resolution.validation_errors:
            lines.append(f"- {err}")
        lines.append("")

    if resolution.content:
        # Show a truncated preview of the suggested resolution.
        preview = resolution.content
        if len(preview) > 500:
            preview = preview[:500] + "\n... (truncated)"

        lines.append("<details>")
        lines.append("<summary>Suggested resolution (click to expand)</summary>")
        lines.append("")
        lines.append("```")
        lines.append(preview)
        lines.append("```")
        lines.append("</details>")

    return "\n".join(lines)
