import fs from 'node:fs';
import path from 'node:path';
import {
  ContentShapeType,
  EnvelopeContentType,
  type TContentHighlightMeta,
  type TContentImageMeta,
  type TContentShapeMeta,
  type TContentTextMeta,
  type TEnvelopeContentMetaInput,
} from '@documenso/lib/types/envelope-content-meta';

/**
 * A content to seed for the visual regression test, laid out on the labelled
 * grid of `assets/content-alignment.pdf` so placement can be read against the
 * printed boxes. Each content type has its own page.
 *
 * The PDF is generated by `scripts/generate-content-alignment-test-pdf.mjs`.
 * Keep `CONTENT_ALIGNMENT_GRID` and `CONTENT_ALIGNMENT_PAGES` in sync with
 * the grid and page order there.
 */
export type ContentTestData = {
  page: number;
  metadata: TEnvelopeContentMetaInput;

  /**
   * An image to attach, for image contents.
   */
  image?: 'logo';

  /**
   * The stacking order among the contents of the page. Defaults to 0, with
   * ties broken by the content's id.
   */
  zIndex?: number;
};

export const CONTENT_ALIGNMENT_PDF = fs.readFileSync(path.join(__dirname, '../../../assets/content-alignment.pdf'));

/**
 * The Documenso wordmark, wide (about 6.8:1) so fitting, centering and
 * rotation are all visible.
 */
export const CONTENT_ALIGNMENT_LOGO_PNG = fs.readFileSync(path.join(__dirname, '../../../packages/assets/logo.png'));

export const CONTENT_ALIGNMENT_PAGES = {
  text: 1,
  line: 2,
  shape: 3,
  highlight: 4,
  image: 5,
} as const;

/**
 * The page is A4, so a square in page units needs the width scaled by this.
 */
const A4_ASPECT = 210 / 297;

/**
 * The grid printed on every page of the PDF, as percentages of the page.
 */
export const CONTENT_ALIGNMENT_GRID = {
  startX: 8,
  startY: 12,
  columnWidth: 28,
  columnGap: 1,
  rowHeight: 7,
  rowGap: 1,
};

const cell = (row: number, column: number, { rows = 1, columns = 1 }: { rows?: number; columns?: number } = {}) => {
  const { startX, startY, columnWidth, columnGap, rowHeight, rowGap } = CONTENT_ALIGNMENT_GRID;

  return {
    positionX: startX + column * (columnWidth + columnGap),
    positionY: startY + row * (rowHeight + rowGap),
    width: columns * columnWidth + (columns - 1) * columnGap,
    height: rows * rowHeight + (rows - 1) * rowGap,
  };
};

type Box = ReturnType<typeof cell>;

/**
 * A box half the size of a cell, placed at the cell's center.
 *
 * Contents rotate about their top left corner (see `ZContentRotationSchema`),
 * so a rotated box placed at a cell's top left would sweep outside the cell.
 * Starting from the center keeps every rotation within the cell.
 */
const halfCell = (row: number, column: number, options: { rows?: number; columns?: number } = {}) => {
  const box = cell(row, column, options);

  return {
    positionX: box.positionX + box.width / 2,
    positionY: box.positionY + box.height / 2,
    width: box.width / 2,
    height: box.height / 2,
  };
};

/**
 * A square box in page units, as tall as the given number of rows.
 */
const square = (row: number, column: number, rows: number) => {
  const box = cell(row, column, { rows });

  return { ...box, width: box.height * A4_ASPECT };
};

// --- Builders ---

type Overrides<T> = Partial<Omit<T, 'type'>>;

const text = (box: Box, meta: Overrides<TContentTextMeta> & { text: string }): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.text,
  metadata: { type: EnvelopeContentType.TEXT, page: CONTENT_ALIGNMENT_PAGES.text, rotation: 0, ...box, ...meta },
});

type LinePoints = { startXPosition: number; startYPosition: number; endXPosition: number; endYPosition: number };

const horizontal = (box: Box): LinePoints => ({
  startXPosition: box.positionX,
  endXPosition: box.positionX + box.width,
  startYPosition: box.positionY + box.height / 2,
  endYPosition: box.positionY + box.height / 2,
});

const line = (
  points: LinePoints,
  meta: { strokeWidth: number; strokeColor?: string; strokeStyle?: 'solid' | 'dashed' | 'dotted' },
): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.line,
  metadata: {
    type: EnvelopeContentType.LINE,
    page: CONTENT_ALIGNMENT_PAGES.line,
    strokeColor: '#000000',
    strokeStyle: 'solid',
    ...points,
    ...meta,
  },
});

const rectangle = (box: Box, meta: Overrides<TContentShapeMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.shape,
  metadata: {
    type: EnvelopeContentType.SHAPE,
    shape: ContentShapeType.RECTANGLE,
    page: CONTENT_ALIGNMENT_PAGES.shape,
    rotation: 0,
    strokeWidth: 1,
    strokeColor: '#000000',
    strokeStyle: 'solid',
    ...box,
    ...meta,
  },
});

const highlight = (box: Box, meta: Overrides<TContentHighlightMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.highlight,
  metadata: {
    type: EnvelopeContentType.HIGHLIGHT,
    page: CONTENT_ALIGNMENT_PAGES.highlight,
    rotation: 0,
    color: '#ffe600',
    opacity: 0.4,
    ...box,
    ...meta,
  },
});

const image = (box: Box, meta: Overrides<TContentImageMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.image,
  image: 'logo',
  metadata: { type: EnvelopeContentType.IMAGE, page: CONTENT_ALIGNMENT_PAGES.image, rotation: 0, ...box, ...meta },
});

// --- Page 1: Text ---

const TEXT_CONTENTS: ContentTestData[] = [
  text(cell(0, 0), { text: 'Left aligned', textAlign: 'left' }),
  text(cell(0, 1), { text: 'Center aligned', textAlign: 'center' }),
  text(cell(0, 2), { text: 'Right aligned', textAlign: 'right' }),

  text(cell(1, 0, { rows: 2 }), { text: 'Top', verticalAlign: 'top' }),
  text(cell(1, 1, { rows: 2 }), { text: 'Middle', verticalAlign: 'middle' }),
  text(cell(1, 2, { rows: 2 }), { text: 'Bottom', verticalAlign: 'bottom' }),

  text(cell(3, 0), { text: 'Size 8', fontSize: 8 }),
  text(cell(3, 1), { text: 'Size 14', fontSize: 14, color: '#d00000' }),
  text(cell(3, 2), { text: 'Size 24 cropped to the box', fontSize: 24 }),

  text(cell(4, 0), { text: 'Two lines of text wrap here', lineHeight: 1.6 }),
  text(cell(4, 1), { text: 'Spaced', letterSpacing: 3 }),
  text(cell(4, 2, { rows: 2 }), {
    text: 'A longer paragraph of text which wraps onto several lines within its box, centered both ways.',
    textAlign: 'center',
    verticalAlign: 'middle',
  }),

  // Rotation pivots on the box's top left corner, so a 90 degree rotation
  // hangs down the left edge of its cell. Inset it so it stays inside.
  text(cell(6, 0, { rows: 2 }), { text: 'Rotated 15', rotation: 15 }),
  text({ ...cell(6, 1, { rows: 2 }), positionX: cell(6, 1).positionX + 8 }, { text: 'Rotated 90', rotation: 90 }),
];

// --- Page 2: Lines ---

const LINE_CONTENTS: ContentTestData[] = [
  line(horizontal(cell(0, 0)), { strokeWidth: 1, strokeStyle: 'solid' }),
  line(horizontal(cell(0, 1)), { strokeWidth: 2, strokeStyle: 'dashed' }),
  line(horizontal(cell(0, 2)), { strokeWidth: 3, strokeStyle: 'dotted' }),

  line(horizontal(cell(1, 0)), { strokeWidth: 0.5 }),
  line(horizontal(cell(1, 1)), { strokeWidth: 5 }),
  line(horizontal(cell(1, 2)), { strokeWidth: 10 }),

  // Diagonals across the full width, corner to corner.
  ...(() => {
    const down = cell(2, 0, { columns: 3, rows: 2 });
    const up = cell(4, 0, { columns: 3, rows: 2 });

    return [
      line(
        {
          startXPosition: down.positionX,
          startYPosition: down.positionY,
          endXPosition: down.positionX + down.width,
          endYPosition: down.positionY + down.height,
        },
        { strokeWidth: 2, strokeColor: '#0055aa' },
      ),
      line(
        {
          startXPosition: up.positionX,
          startYPosition: up.positionY + up.height,
          endXPosition: up.positionX + up.width,
          endYPosition: up.positionY,
        },
        { strokeWidth: 2, strokeColor: '#0055aa', strokeStyle: 'dashed' },
      ),
    ];
  })(),

  // Vertical lines: through the center, along the left edge, and colored.
  ...(() => {
    const center = cell(6, 0, { rows: 2 });
    const edge = cell(6, 1, { rows: 2 });
    const red = cell(6, 2, { rows: 2 });

    return [
      line(
        {
          startXPosition: center.positionX + center.width / 2,
          startYPosition: center.positionY,
          endXPosition: center.positionX + center.width / 2,
          endYPosition: center.positionY + center.height,
        },
        { strokeWidth: 2 },
      ),
      line(
        {
          startXPosition: edge.positionX,
          startYPosition: edge.positionY,
          endXPosition: edge.positionX,
          endYPosition: edge.positionY + edge.height,
        },
        { strokeWidth: 4 },
      ),
      line(
        {
          startXPosition: red.positionX + red.width / 2,
          startYPosition: red.positionY,
          endXPosition: red.positionX + red.width / 2,
          endYPosition: red.positionY + red.height,
        },
        { strokeWidth: 3, strokeColor: '#d00000', strokeStyle: 'dotted' },
      ),
    ];
  })(),
];

/**
 * Two overlapping filled rectangles within a cell, for stacking tests. The
 * second is offset down and right of the first so both are partly visible
 * and the overlap shows which is on top.
 */
const stackedPair = (
  row: number,
  column: number,
  { first, second }: { first: { fillColor: string; zIndex: number }; second: { fillColor: string; zIndex: number } },
): ContentTestData[] => {
  const box = cell(row, column, { rows: 2 });
  const size = { width: box.width * 0.6, height: box.height * 0.6 };

  return [
    {
      ...rectangle(
        { positionX: box.positionX, positionY: box.positionY, ...size },
        { fillColor: first.fillColor, fillOpacity: 1, strokeWidth: 1 },
      ),
      zIndex: first.zIndex,
    },
    {
      ...rectangle(
        { positionX: box.positionX + box.width * 0.4, positionY: box.positionY + box.height * 0.4, ...size },
        { fillColor: second.fillColor, fillOpacity: 1, strokeWidth: 1 },
      ),
      zIndex: second.zIndex,
    },
  ];
};

// --- Page 3: Shapes ---

const SHAPE_CONTENTS: ContentTestData[] = [
  rectangle(cell(0, 0), { strokeWidth: 2, strokeColor: '#d00000' }),
  rectangle(cell(0, 1), { strokeWidth: 1, strokeStyle: 'dashed' }),
  rectangle(cell(0, 2), { strokeWidth: 4, strokeStyle: 'dotted' }),

  rectangle(cell(1, 0), { fillColor: '#ffcc00', fillOpacity: 1 }),
  rectangle(cell(1, 1), { fillColor: '#00aa55', fillOpacity: 0.4 }),
  rectangle(cell(1, 2), { fillColor: '#0055aa', fillOpacity: 1, strokeWidth: 0.5, strokeColor: '#0055aa' }),

  rectangle(square(2, 0, 2), { strokeWidth: 2 }),
  rectangle(cell(2, 1, { columns: 2 }), { strokeWidth: 1, fillColor: '#e5e7eb', fillOpacity: 1 }),

  // Rotation pivots on the box's top left corner. Half sized boxes placed
  // towards the right of their cells keep the swept shape within the cell.
  rectangle(halfCell(4, 0, { rows: 2 }), { strokeWidth: 2, strokeColor: '#d00000', rotation: 15 }),
  rectangle(halfCell(4, 1, { rows: 2 }), { strokeWidth: 2, strokeColor: '#00aa55', rotation: 45 }),
  rectangle(halfCell(4, 2, { rows: 2 }), { strokeWidth: 2, strokeColor: '#0055aa', rotation: 90 }),

  // Stacking. Each cell holds two overlapping filled rectangles: the first
  // (top left) and the second (offset to the bottom right). The rectangles
  // are listed, and therefore created, in that order, and the seed hands out
  // ids in that same order so equal zIndexes stack the second on top.
  //
  // Expected on top: red, blue, green.
  ...stackedPair(6, 0, { first: { fillColor: '#d00000', zIndex: 2 }, second: { fillColor: '#ffcc00', zIndex: 1 } }),
  ...stackedPair(6, 1, { first: { fillColor: '#ffcc00', zIndex: 0 }, second: { fillColor: '#0055aa', zIndex: 5 } }),
  ...stackedPair(6, 2, { first: { fillColor: '#d00000', zIndex: 3 }, second: { fillColor: '#00aa55', zIndex: 3 } }),
];

// --- Page 4: Highlights ---

const HIGHLIGHT_CONTENTS: ContentTestData[] = [
  highlight(cell(0, 0), { color: '#ffe600' }),
  highlight(cell(0, 1), { color: '#00aa55' }),
  highlight(cell(0, 2), { color: '#ff66cc' }),

  highlight(cell(1, 0), { opacity: 0.1 }),
  highlight(cell(1, 1), { opacity: 0.6 }),
  highlight(cell(1, 2), { opacity: 1 }),

  highlight(cell(2, 0, { columns: 3 })),

  highlight(halfCell(3, 0, { rows: 2 }), { rotation: 15 }),
  highlight(halfCell(3, 1, { rows: 2 }), { rotation: 45 }),
];

// --- Page 5: Images ---

const IMAGE_CONTENTS: ContentTestData[] = [
  // Fit: the wide logo fills a wide box, letterboxes in a square, centers in a tall one.
  image(cell(0, 0, { rows: 2 })),
  image(square(0, 1, 2)),
  image({ ...cell(0, 2, { rows: 3 }), width: cell(0, 2).width / 2 }),

  image(cell(3, 0, { columns: 3, rows: 2 })),

  // Rotation pivots on the box's top left corner. Half sized boxes placed
  // towards the right of their cells keep the swept image within the cell.
  image(halfCell(5, 0, { rows: 2 }), { rotation: 15 }),
  image(halfCell(5, 1, { rows: 2 }), { rotation: 45 }),
  image(halfCell(5, 2, { rows: 2 }), { rotation: 90 }),

  image(halfCell(7, 0, { rows: 2 }), { rotation: 180 }),
  image(halfCell(7, 1, { rows: 2 }), { rotation: 270 }),
];

export const CONTENT_ALIGNMENT_TEST_CONTENTS: ContentTestData[] = [
  ...TEXT_CONTENTS,
  ...LINE_CONTENTS,
  ...SHAPE_CONTENTS,
  ...HIGHLIGHT_CONTENTS,
  ...IMAGE_CONTENTS,
];
