import fs from 'node:fs';
import path from 'node:path';
import {
  EnvelopeContentShapeType,
  EnvelopeContentType,
  type TContentHighlightMeta,
  type TContentImageMeta,
  type TContentShapeMeta,
  type TContentTextMeta,
  type TEnvelopeContentMetaInput,
} from '@documenso/lib/types/envelope-content-meta';

/**
 * A content to seed for the visual regression test, laid out on the labelled
 * grid of `assets/content-alignment.pdf` so placement can be read against the
 * printed boxes. Each content type has its own page.
 *
 * The PDF is generated by `scripts/generate-content-alignment-test-pdf.mjs`.
 * Keep `CONTENT_ALIGNMENT_GRID` and `CONTENT_ALIGNMENT_PAGES` in sync with
 * the grid and page order there.
 */
export type ContentTestData = {
  page: number;
  contentMeta: TEnvelopeContentMetaInput;

  /**
   * An image to attach, for image contents.
   */
  image?: 'logo';
};

export const CONTENT_ALIGNMENT_PDF = fs.readFileSync(path.join(__dirname, '../../../assets/content-alignment.pdf'));

/**
 * The Documenso wordmark, wide (about 6.8:1) so fitting, centering and
 * rotation are all visible.
 */
export const CONTENT_ALIGNMENT_LOGO_PNG = fs.readFileSync(path.join(__dirname, '../../../packages/assets/logo.png'));

export const CONTENT_ALIGNMENT_PAGES = {
  text: 1,
  line: 2,
  shape: 3,
  highlight: 4,
  image: 5,
} as const;

/**
 * The size of the PDF's pages in points, the unit contents are drawn in.
 *
 * Positions are percentages of the page's width and height, which are not the
 * same length, so anything which has to keep its shape (a square, a rotation)
 * is worked out in points.
 */
const PAGE_SIZE = { width: 595.92, height: 842.88 };

const toPointsX = (percent: number) => (percent / 100) * PAGE_SIZE.width;
const toPointsY = (percent: number) => (percent / 100) * PAGE_SIZE.height;
const toPercentX = (points: number) => (points / PAGE_SIZE.width) * 100;
const toPercentY = (points: number) => (points / PAGE_SIZE.height) * 100;

/**
 * The grid printed on every page of the PDF, as percentages of the page.
 */
export const CONTENT_ALIGNMENT_GRID = {
  startX: 8,
  startY: 12,
  columnWidth: 28,
  columnGap: 1,
  rowHeight: 7,
  // Holds each box's label, which the PDF prints just above the box.
  rowGap: 2,
};

const cell = (row: number, column: number, { rows = 1, columns = 1 }: { rows?: number; columns?: number } = {}) => {
  const { startX, startY, columnWidth, columnGap, rowHeight, rowGap } = CONTENT_ALIGNMENT_GRID;

  return {
    positionX: startX + column * (columnWidth + columnGap),
    positionY: startY + row * (rowHeight + rowGap),
    width: columns * columnWidth + (columns - 1) * columnGap,
    height: rows * rowHeight + (rows - 1) * rowGap,
  };
};

/**
 * The box of a grid cell as printed on the PDF, for anything else placed on
 * it, e.g. the seed's signature field.
 */
export const getContentAlignmentCell = cell;

type Box = ReturnType<typeof cell>;

/**
 * The box of a content which can be rotated, i.e. a shape or an image.
 */
type RotatableBox = Box & { rotation?: number };

/**
 * A box half the size of a cell, rotated by `rotation` and centered in the
 * cell.
 *
 * Contents rotate about their top left corner (see `ZContentRotationSchema`),
 * so that corner is placed wherever the rotation needs it for the box's center
 * to land on the cell's center. Throws if the rotated box would not fit in the
 * cell, since it would then reach into the neighbouring cells.
 */
const rotatedHalfCell = (
  row: number,
  column: number,
  rotation: number,
  options: { rows?: number; columns?: number } = {},
): RotatableBox => {
  const box = cell(row, column, options);

  const width = box.width / 2;
  const height = box.height / 2;

  // Half the box's width and height, in points.
  const halfWidth = toPointsX(width) / 2;
  const halfHeight = toPointsY(height) / 2;

  const radians = (rotation * Math.PI) / 180;
  const cos = Math.cos(radians);
  const sin = Math.sin(radians);

  // Where the box's center ends up, relative to its top left corner.
  const centerX = halfWidth * cos - halfHeight * sin;
  const centerY = halfWidth * sin + halfHeight * cos;

  // How far the rotated box reaches from its center along each axis.
  const reachX = Math.abs(halfWidth * cos) + Math.abs(halfHeight * sin);
  const reachY = Math.abs(halfWidth * sin) + Math.abs(halfHeight * cos);

  const cellWidth = toPointsX(box.width);
  const cellHeight = toPointsY(box.height);

  if (reachX * 2 > cellWidth || reachY * 2 > cellHeight) {
    throw new Error(`A half size box rotated by ${rotation} degrees does not fit in cell ${row}, ${column}`);
  }

  return {
    positionX: box.positionX + toPercentX(cellWidth / 2 - centerX),
    positionY: box.positionY + toPercentY(cellHeight / 2 - centerY),
    width,
    height,
    rotation,
  };
};

/**
 * A square box as tall as the given number of rows.
 */
const square = (row: number, column: number, rows: number): Box => {
  const box = cell(row, column, { rows });

  return { ...box, width: toPercentX(toPointsY(box.height)) };
};

// --- Builders ---

type Overrides<T> = Partial<Omit<T, 'type'>>;

const text = (box: Box, meta: Overrides<TContentTextMeta> & { text: string }): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.text,
  contentMeta: { type: EnvelopeContentType.TEXT, page: CONTENT_ALIGNMENT_PAGES.text, ...box, ...meta },
});

type LinePoints = { x1: number; y1: number; x2: number; y2: number };

type LineMeta = { strokeWidth: number; strokeColor?: string; strokeStyle?: 'solid' | 'dashed' | 'dotted' };

const line = (points: LinePoints, meta: LineMeta): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.line,
  contentMeta: {
    type: EnvelopeContentType.LINE,
    page: CONTENT_ALIGNMENT_PAGES.line,
    strokeColor: '#000000',
    strokeStyle: 'solid',
    ...points,
    ...meta,
  },
});

/**
 * A horizontal line across the middle of a box.
 *
 * Round line ends reach past the line's points by half its width, so the
 * points are pulled in by that much to keep the whole line within its box.
 * Otherwise thick lines in neighbouring columns join across the gap.
 */
const horizontalLine = (box: Box, meta: LineMeta): ContentTestData => {
  const inset = toPercentX(meta.strokeWidth / 2);
  const y = box.positionY + box.height / 2;

  return line({ x1: box.positionX + inset, y1: y, x2: box.positionX + box.width - inset, y2: y }, meta);
};

const rectangle = (box: RotatableBox, meta: Overrides<TContentShapeMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.shape,
  contentMeta: {
    type: EnvelopeContentType.SHAPE,
    shape: EnvelopeContentShapeType.RECTANGLE,
    page: CONTENT_ALIGNMENT_PAGES.shape,
    rotation: 0,
    strokeWidth: 1,
    strokeColor: '#000000',
    strokeStyle: 'solid',
    ...box,
    ...meta,
  },
});

const highlight = (box: Box, meta: Overrides<TContentHighlightMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.highlight,
  contentMeta: {
    type: EnvelopeContentType.HIGHLIGHT,
    page: CONTENT_ALIGNMENT_PAGES.highlight,
    color: '#ffe600',
    fillOpacity: 0.4,
    ...box,
    ...meta,
  },
});

const image = (box: RotatableBox, meta: Overrides<TContentImageMeta> = {}): ContentTestData => ({
  page: CONTENT_ALIGNMENT_PAGES.image,
  image: 'logo',
  contentMeta: { type: EnvelopeContentType.IMAGE, page: CONTENT_ALIGNMENT_PAGES.image, rotation: 0, ...box, ...meta },
});

// --- Page 1: Text ---

const TEXT_CONTENTS: ContentTestData[] = [
  text(cell(0, 0), { text: 'Left aligned', textAlign: 'left' }),
  text(cell(0, 1), { text: 'Center aligned', textAlign: 'center' }),
  text(cell(0, 2), { text: 'Right aligned', textAlign: 'right' }),

  text(cell(1, 0, { rows: 2 }), { text: 'Top', verticalAlign: 'top' }),
  text(cell(1, 1, { rows: 2 }), { text: 'Middle', verticalAlign: 'middle' }),
  text(cell(1, 2, { rows: 2 }), { text: 'Bottom', verticalAlign: 'bottom' }),

  text(cell(3, 0), { text: 'Size 8', fontSize: 8 }),
  text(cell(3, 1), { text: 'Size 14', fontSize: 14, color: '#d00000' }),
  text(cell(3, 2), { text: 'Size 24 cropped to the box', fontSize: 24 }),

  // Long enough to wrap, so the line height shows in the gap between the lines.
  text(cell(4, 0), { text: 'Two lines of text, wrapped and spaced apart by the line height', lineHeight: 1.6 }),
  text(cell(4, 1), { text: 'Spaced', letterSpacing: 3 }),
  text(cell(4, 2, { rows: 2 }), {
    text: 'A longer paragraph of text which wraps onto several lines within its box, centered both ways.',
    textAlign: 'center',
    verticalAlign: 'middle',
  }),
];

// --- Page 2: Lines ---

const LINE_CONTENTS: ContentTestData[] = [
  horizontalLine(cell(0, 0), { strokeWidth: 1, strokeStyle: 'solid' }),
  horizontalLine(cell(0, 1), { strokeWidth: 2, strokeStyle: 'dashed' }),
  horizontalLine(cell(0, 2), { strokeWidth: 3, strokeStyle: 'dotted' }),

  horizontalLine(cell(1, 0), { strokeWidth: 0.5 }),
  horizontalLine(cell(1, 1), { strokeWidth: 5 }),
  horizontalLine(cell(1, 2), { strokeWidth: 10 }),

  // Diagonals across the full width, corner to corner.
  ...(() => {
    const down = cell(2, 0, { columns: 3, rows: 2 });
    const up = cell(4, 0, { columns: 3, rows: 2 });

    return [
      line(
        {
          x1: down.positionX,
          y1: down.positionY,
          x2: down.positionX + down.width,
          y2: down.positionY + down.height,
        },
        { strokeWidth: 2, strokeColor: '#0055aa' },
      ),
      line(
        {
          x1: up.positionX,
          y1: up.positionY + up.height,
          x2: up.positionX + up.width,
          y2: up.positionY,
        },
        { strokeWidth: 2, strokeColor: '#0055aa', strokeStyle: 'dashed' },
      ),
    ];
  })(),

  // Vertical lines: through the center, along the left edge, and colored.
  ...(() => {
    const center = cell(6, 0, { rows: 2 });
    const edge = cell(6, 1, { rows: 2 });
    const red = cell(6, 2, { rows: 2 });

    return [
      line(
        {
          x1: center.positionX + center.width / 2,
          y1: center.positionY,
          x2: center.positionX + center.width / 2,
          y2: center.positionY + center.height,
        },
        { strokeWidth: 2 },
      ),
      line(
        {
          x1: edge.positionX,
          y1: edge.positionY,
          x2: edge.positionX,
          y2: edge.positionY + edge.height,
        },
        { strokeWidth: 4 },
      ),
      line(
        {
          x1: red.positionX + red.width / 2,
          y1: red.positionY,
          x2: red.positionX + red.width / 2,
          y2: red.positionY + red.height,
        },
        { strokeWidth: 3, strokeColor: '#d00000', strokeStyle: 'dotted' },
      ),
    ];
  })(),
];

/**
 * Two overlapping filled rectangles within a cell, for stacking tests. The
 * second is offset down and right of the first so both are partly visible
 * and the overlap shows which is on top.
 */
const stackedPair = (
  row: number,
  column: number,
  { first, second }: { first: { fillColor: string; zIndex: number }; second: { fillColor: string; zIndex: number } },
): ContentTestData[] => {
  const box = cell(row, column, { rows: 2 });
  const size = { width: box.width * 0.6, height: box.height * 0.6 };

  return [
    rectangle(
      { positionX: box.positionX, positionY: box.positionY, ...size },
      { fillColor: first.fillColor, fillOpacity: 1, strokeWidth: 1, zIndex: first.zIndex },
    ),
    rectangle(
      { positionX: box.positionX + box.width * 0.4, positionY: box.positionY + box.height * 0.4, ...size },
      { fillColor: second.fillColor, fillOpacity: 1, strokeWidth: 1, zIndex: second.zIndex },
    ),
  ];
};

// --- Page 3: Shapes ---

const SHAPE_CONTENTS: ContentTestData[] = [
  rectangle(cell(0, 0), { strokeWidth: 2, strokeColor: '#d00000' }),
  rectangle(cell(0, 1), { strokeWidth: 1, strokeStyle: 'dashed' }),
  rectangle(cell(0, 2), { strokeWidth: 4, strokeStyle: 'dotted' }),

  rectangle(cell(1, 0), { fillColor: '#ffcc00', fillOpacity: 1 }),
  rectangle(cell(1, 1), { fillColor: '#00aa55', fillOpacity: 0.4 }),
  rectangle(cell(1, 2), { fillColor: '#0055aa', fillOpacity: 1, strokeWidth: 0.5, strokeColor: '#0055aa' }),

  rectangle(square(2, 0, 2), { strokeWidth: 2 }),
  rectangle(cell(2, 1, { columns: 2 }), { strokeWidth: 1, fillColor: '#e5e7eb', fillOpacity: 1 }),

  // Each rotated shape is centered in its cell, clear of the stacking row.
  rectangle(rotatedHalfCell(4, 0, 15, { rows: 2 }), { strokeWidth: 2, strokeColor: '#d00000' }),
  rectangle(rotatedHalfCell(4, 1, 45, { rows: 2 }), { strokeWidth: 2, strokeColor: '#00aa55' }),
  rectangle(rotatedHalfCell(4, 2, 90, { rows: 2 }), { strokeWidth: 2, strokeColor: '#0055aa' }),

  // Stacking. Each cell holds two overlapping filled rectangles: the first
  // (top left) and the second (offset to the bottom right). The rectangles
  // are listed, and therefore created, in that order, and the seed hands out
  // ids in that same order so equal zIndexes stack the second on top.
  //
  // Expected on top: red, blue, green.
  ...stackedPair(6, 0, { first: { fillColor: '#d00000', zIndex: 2 }, second: { fillColor: '#ffcc00', zIndex: 1 } }),
  ...stackedPair(6, 1, { first: { fillColor: '#ffcc00', zIndex: 0 }, second: { fillColor: '#0055aa', zIndex: 5 } }),
  ...stackedPair(6, 2, { first: { fillColor: '#d00000', zIndex: 3 }, second: { fillColor: '#00aa55', zIndex: 3 } }),
];

// --- Page 4: Highlights ---

const HIGHLIGHT_CONTENTS: ContentTestData[] = [
  highlight(cell(0, 0), { color: '#ffe600' }),
  highlight(cell(0, 1), { color: '#00aa55' }),
  highlight(cell(0, 2), { color: '#ff66cc' }),

  highlight(cell(1, 0), { fillOpacity: 0.1 }),
  highlight(cell(1, 1), { fillOpacity: 0.6 }),
  highlight(cell(1, 2), { fillOpacity: 1 }),

  highlight(cell(2, 0, { columns: 3 })),
];

// --- Page 5: Images ---

const IMAGE_CONTENTS: ContentTestData[] = [
  // Fit: the wide logo fills a wide box, letterboxes in a square, centers in a tall one.
  image(cell(0, 0, { rows: 2 })),
  image(square(0, 1, 2)),
  image({ ...cell(0, 2, { rows: 3 }), width: cell(0, 2).width / 2 }),

  image(cell(3, 0, { columns: 3, rows: 2 })),

  // Each rotated image is centered in its cell, clear of its neighbours.
  image(rotatedHalfCell(5, 0, 15, { rows: 2 })),
  image(rotatedHalfCell(5, 1, 45, { rows: 2 })),
  image(rotatedHalfCell(5, 2, 90, { rows: 2 })),

  image(rotatedHalfCell(7, 0, 180, { rows: 2 })),
  image(rotatedHalfCell(7, 1, 270, { rows: 2 })),
];

export const CONTENT_ALIGNMENT_TEST_CONTENTS: ContentTestData[] = [
  ...TEXT_CONTENTS,
  ...LINE_CONTENTS,
  ...SHAPE_CONTENTS,
  ...HIGHLIGHT_CONTENTS,
  ...IMAGE_CONTENTS,
];
