'apps: web':
  - apps/remix/**

'type: documentation'
  - apps/docs/**

'version bump 👀':
  - '**/package.json'
  - '**/package-lock.json'

'🚨 migrations 🚨':
  - packages/prisma/migrations/**/migration.sql

'🚨 e2e changes 🚨':
  - packages/app-tests/e2e/**

'🚨 .env changes 🚨':
  - .env.example

'pkg: ee changes':
  - packages/ee/**
