packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # Core
  react: ^19.2.4
  react-dom: ^19.2.4
  typescript: 5.6.2
  zod: ^3.25.76

  # Shared utilities
  ts-pattern: ^5.9.0
  luxon: ^3.7.2
  nanoid: ^5.1.6
  remeda: ^2.32.0
  superjson: ^2.2.5

  # AWS
  '@aws-sdk/client-s3': ^3.998.0
  '@aws-sdk/client-sesv2': ^3.998.0
  '@aws-sdk/cloudfront-signer': ^3.998.0
  '@aws-sdk/s3-request-presigner': ^3.998.0
  '@aws-sdk/signature-v4-crt': ^3.998.0

  # Framework
  next: 16.1.6
  hono: ^4.12.2
  '@hono/standard-validator': ^0.2.0
  '@tanstack/react-query': 5.90.10
  '@trpc/client': 11.8.1
  '@trpc/react-query': 11.8.1
  '@trpc/server': 11.8.1
  '@ts-rest/core': ^3.52.1
  '@ts-rest/open-api': ^3.52.1
  '@ts-rest/serverless': ^3.52.1

  # UI
  framer-motion: ^12.23.24
  lucide-react: ^0.563.0
  react-hook-form: ^7.66.1
  '@hookform/resolvers': ^3
  '@radix-ui/react-accordion': ^1.2.12
  '@radix-ui/react-alert-dialog': ^1.1.15
  '@radix-ui/react-aspect-ratio': ^1.1.8
  '@radix-ui/react-avatar': ^1.1.11
  '@radix-ui/react-checkbox': ^1.3.3
  '@radix-ui/react-collapsible': ^1.1.12
  '@radix-ui/react-context-menu': ^2.2.16
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-dropdown-menu': ^2.1.16
  '@radix-ui/react-hover-card': ^1.1.15
  '@radix-ui/react-label': ^2.1.8
  '@radix-ui/react-menubar': ^1.1.16
  '@radix-ui/react-navigation-menu': ^1.2.14
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-radio-group': ^1.3.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-select': ^2.2.6
  '@radix-ui/react-separator': ^1.1.8
  '@radix-ui/react-slider': ^1.3.6
  '@radix-ui/react-slot': ^1.2.4
  '@radix-ui/react-switch': ^1.2.6
  '@radix-ui/react-tabs': ^1.1.13
  '@radix-ui/react-toast': ^1.2.15
  '@radix-ui/react-toggle': ^1.1.10
  '@radix-ui/react-toggle-group': ^1.1.11
  '@radix-ui/react-tooltip': ^1.2.8
  react-rnd: ^10.5.2
  react-pdf: ^10.3.0
  konva: ^10.0.9
  '@napi-rs/canvas': ^0.1.83
  postcss: ^8.5.6
  tailwindcss: ^3.4.18
  autoprefixer: ^10.4.22
  tailwindcss-animate: ^1.0.7

  # i18n
  '@lingui/core': ^5.6.0
  '@lingui/macro': ^5.6.0
  '@lingui/react': ^5.6.0

  # Auth
  '@simplewebauthn/server': ^13.2.2
  '@oslojs/crypto': ^1.0.1
  '@oslojs/encoding': ^1.1.0

  # Crypto
  '@scure/base': ^1.2.6

  # AI
  '@ai-sdk/google-vertex': 3.0.81
  ai: ^5.0.104

  # Email
  nodemailer: ^7.0.10

  # Observability
  posthog-node: 4.18.0
  posthog-js: ^1.297.2
  pino: ^9.14.0
  pino-pretty: ^13.1.2

  # Database
  kysely: 0.28.8
  '@prisma/client': ^6.19.0
  prisma: ^6.19.0
  prisma-extension-kysely: ^3.0.0
  prisma-json-types-generator: ^3.6.2
  prisma-kysely: ^2.3.0
  zod-prisma-types: 3.3.5

  # Build tools
  tsx: ^4.20.6
  vite: ^7.2.4
  eslint: ^8.57.0
  prettier: ^3.6.2
  dotenv: ^17.2.3
  dotenv-cli: ^11.0.0

  # PDF / Documents
  pdfjs-dist: 5.4.296

  # Testing
  playwright: 1.56.1

  # API
  zod-openapi: ^4.2.4

  # Types
  '@types/react': ^19
  '@types/react-dom': ^19
  '@types/node': ^22
  '@types/luxon': ^3.7.1
  '@types/formidable': ^3.4.6
