export const isErrorCode = (code: unknown): code is ErrorCode => {
  return typeof code === 'string' && code in ErrorCode;
};

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const ErrorCode = {
  INCORRECT_EMAIL_PASSWORD: 'INCORRECT_EMAIL_PASSWORD',
  USER_MISSING_PASSWORD: 'USER_MISSING_PASSWORD',
  CREDENTIALS_NOT_FOUND: 'CREDENTIALS_NOT_FOUND',
  INTERNAL_SEVER_ERROR: 'INTERNAL_SEVER_ERROR',
  TWO_FACTOR_ALREADY_ENABLED: 'TWO_FACTOR_ALREADY_ENABLED',
  TWO_FACTOR_SETUP_REQUIRED: 'TWO_FACTOR_SETUP_REQUIRED',
  TWO_FACTOR_MISSING_SECRET: 'TWO_FACTOR_MISSING_SECRET',
  TWO_FACTOR_MISSING_CREDENTIALS: 'TWO_FACTOR_MISSING_CREDENTIALS',
  INCORRECT_TWO_FACTOR_CODE: 'INCORRECT_TWO_FACTOR_CODE',
  INCORRECT_TWO_FACTOR_BACKUP_CODE: 'INCORRECT_TWO_FACTOR_BACKUP_CODE',
  INCORRECT_IDENTITY_PROVIDER: 'INCORRECT_IDENTITY_PROVIDER',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  MISSING_ENCRYPTION_KEY: 'MISSING_ENCRYPTION_KEY',
  MISSING_BACKUP_CODE: 'MISSING_BACKUP_CODE',
  UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
} as const;
