import { createEnv } from '@t3-oss/env-nextjs';
import { z } from 'zod';

const {
  NEXTAUTH_URL,
  NEXTAUTH_SECRET,

  // AUTH OPTIONAL
  NEXT_PRIVATE_GOOGLE_CLIENT_ID,
  NEXT_PRIVATE_GOOGLE_CLIENT_SECRET,

  // DATABASE
  NEXT_PRIVATE_DATABASE_URL,
  NEXT_PRIVATE_DIRECT_DATABASE_URL,

  // STORAGe S3
  NEXT_PUBLIC_UPLOAD_TRANSPORT,
  NEXT_PRIVATE_UPLOAD_ENDPOINT,
  NEXT_PRIVATE_UPLOAD_REGION,
  NEXT_PRIVATE_UPLOAD_BUCKET,
  NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID,
  NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY,

  // SMTP
  NEXT_PRIVATE_SMTP_TRANSPORT,
  NEXT_PRIVATE_SMTP_HOST,
  NEXT_PRIVATE_SMTP_PORT,
  NEXT_PRIVATE_SMTP_USERNAME,
  NEXT_PRIVATE_SMTP_PASSWORD,
  NEXT_PRIVATE_SMTP_APIKEY_USER,
  NEXT_PRIVATE_SMTP_APIKEY,
  NEXT_PRIVATE_SMTP_SECURE,
  NEXT_PRIVATE_SMTP_FROM_NAME,
  NEXT_PRIVATE_SMTP_FROM_ADDRESS,
  NEXT_PRIVATE_MAILCHANNELS_API_KEY,
  NEXT_PRIVATE_MAILCHANNELS_ENDPOINT,
  NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN,
  NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR,
  NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY,

  // Stripe
  NEXT_PRIVATE_STRIPE_API_KEY,
  NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET,
  NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID,
  NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_YEARLY_PRICE_ID,

  // URLS
  NEXT_PUBLIC_SITE_URL,
  NEXT_PUBLIC_APP_URL,

  // FEATURES
  NEXT_PUBLIC_POSTHOG_KEY,
  NEXT_PUBLIC_POSTHOG_HOST,
  NEXT_PUBLIC_FEATURE_BILLING_ENABLED,
} = process.env;

export const env = createEnv({
  server: {
    // AUTH
    NEXTAUTH_URL: z.string().url(),
    NEXTAUTH_SECRET: z.string(),

    // AUTH OPTIONAL
    NEXT_PRIVATE_GOOGLE_CLIENT_ID: z.string().optional(),
    NEXT_PRIVATE_GOOGLE_CLIENT_SECRET: z.string().optional(),

    // DATABASE
    NEXT_PRIVATE_DATABASE_URL: z.string(),
    NEXT_PRIVATE_DIRECT_DATABASE_URL: z.string(),

    // STORAGe S3
    NEXT_PRIVATE_UPLOAD_ENDPOINT: z.string().optional(),
    NEXT_PRIVATE_UPLOAD_REGION: z.string().optional(),
    NEXT_PRIVATE_UPLOAD_BUCKET: z.string().optional(),
    NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID: z.string().optional(),
    NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY: z.string().optional(),

    // SMTP
    NEXT_PRIVATE_SMTP_TRANSPORT: z.string().optional(),
    NEXT_PRIVATE_SMTP_HOST: z.string().optional(),
    NEXT_PRIVATE_SMTP_PORT: z.coerce.number().optional(),
    NEXT_PRIVATE_SMTP_USERNAME: z.string().optional(),
    NEXT_PRIVATE_SMTP_PASSWORD: z.string().optional(),
    NEXT_PRIVATE_SMTP_APIKEY_USER: z.string().optional(),
    NEXT_PRIVATE_SMTP_APIKEY: z.string().optional(),
    NEXT_PRIVATE_SMTP_SECURE: z.string().optional(),
    NEXT_PRIVATE_SMTP_FROM_NAME: z.string(),
    NEXT_PRIVATE_SMTP_FROM_ADDRESS: z.string(),
    NEXT_PRIVATE_MAILCHANNELS_API_KEY: z.string().optional(),
    NEXT_PRIVATE_MAILCHANNELS_ENDPOINT: z.string().optional(),
    NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN: z.string().optional(),
    NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR: z.string().optional(),
    NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY: z.string().optional(),

    // STRIPE
    NEXT_PRIVATE_STRIPE_API_KEY: z.string().optional(),
    NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET: z.string().optional(),
  },
  /**
   * Specify your client-side environment variables schema here.
   * For them to be exposed to the client, prefix them with `NEXT_PUBLIC_`.
   */
  client: {
    // URLS
    NEXT_PUBLIC_SITE_URL: z.string(),
    NEXT_PUBLIC_APP_URL: z.string(),

    // STORAGE
    NEXT_PUBLIC_UPLOAD_TRANSPORT: z.enum(['database', 's3']),

    // STRIPE
    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID: z.string().optional(),
    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_YEARLY_PRICE_ID: z.string().optional(),

    // FEATURES
    NEXT_PUBLIC_POSTHOG_KEY: z.string().optional(),
    NEXT_PUBLIC_POSTHOG_HOST: z.string().optional(),
    NEXT_PUBLIC_FEATURE_BILLING_ENABLED: z.coerce.boolean().optional(),
  },
  runtimeEnv: {
    NEXTAUTH_URL,
    NEXTAUTH_SECRET,

    // AUTH OPTIONAL
    NEXT_PRIVATE_GOOGLE_CLIENT_ID,
    NEXT_PRIVATE_GOOGLE_CLIENT_SECRET,

    // DATABASE
    NEXT_PRIVATE_DATABASE_URL,
    NEXT_PRIVATE_DIRECT_DATABASE_URL,

    // STORAGe S3
    NEXT_PUBLIC_UPLOAD_TRANSPORT,
    NEXT_PRIVATE_UPLOAD_ENDPOINT,
    NEXT_PRIVATE_UPLOAD_REGION,
    NEXT_PRIVATE_UPLOAD_BUCKET,
    NEXT_PRIVATE_UPLOAD_ACCESS_KEY_ID,
    NEXT_PRIVATE_UPLOAD_SECRET_ACCESS_KEY,

    // SMTP
    NEXT_PRIVATE_SMTP_TRANSPORT,
    NEXT_PRIVATE_SMTP_HOST,
    NEXT_PRIVATE_SMTP_PORT,
    NEXT_PRIVATE_SMTP_USERNAME,
    NEXT_PRIVATE_SMTP_PASSWORD,
    NEXT_PRIVATE_SMTP_APIKEY_USER,
    NEXT_PRIVATE_SMTP_APIKEY,
    NEXT_PRIVATE_SMTP_SECURE,
    NEXT_PRIVATE_SMTP_FROM_NAME,
    NEXT_PRIVATE_SMTP_FROM_ADDRESS,
    NEXT_PRIVATE_MAILCHANNELS_API_KEY,
    NEXT_PRIVATE_MAILCHANNELS_ENDPOINT,
    NEXT_PRIVATE_MAILCHANNELS_DKIM_DOMAIN,
    NEXT_PRIVATE_MAILCHANNELS_DKIM_SELECTOR,
    NEXT_PRIVATE_MAILCHANNELS_DKIM_PRIVATE_KEY,

    // Stripe
    NEXT_PRIVATE_STRIPE_API_KEY,
    NEXT_PRIVATE_STRIPE_WEBHOOK_SECRET,
    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_MONTHLY_PRICE_ID,
    NEXT_PUBLIC_STRIPE_COMMUNITY_PLAN_YEARLY_PRICE_ID,

    // URLS
    NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_APP_URL,

    // FEATURES
    NEXT_PUBLIC_POSTHOG_KEY,
    NEXT_PUBLIC_POSTHOG_HOST,
    NEXT_PUBLIC_FEATURE_BILLING_ENABLED,
  },
});
