name: Cache production build binaries
description: 'Cache or restore if necessary'
inputs:
  node_version:
    required: false
    default: v20.x
runs:
  using: 'composite'
  steps:
    - name: Cache production build
      uses: actions/cache@v3
      id: production-build-cache
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/marketing/.next
          **/.turbo/**
          **/dist/**

        key: prod-build-${{ github.run_id }}-${{ hashFiles('package-lock.json') }}
        restore-keys: prod-build-

    - run: npm run build
      shell: bash
